spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5430/hr
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    path: /error
  whitelabel:
    enabled: false
